# Target folder paths on your external E: drive
storeDir: "E:\\.pnpm-store"
virtualStoreDir: "node_modules/.pnpm"

# Whitelist 
allowBuilds:
  sharp: true

packages:
  - "apps/*"
  - "packages/*"

# pnpm v11 Configuration Engine
publicHoistPattern:
  - "*"

patchedDependencies:
  '@react-aria/i18n@3.13.0': patches/@react-aria__i18n@3.13.0.patch
